@baseUrl = http://140.112.183.138:3000


###
# ROS LiDAR data upload
###
POST {{baseUrl}}/lidar/lidar2dData/ HTTP/1.1
content-type: application/json

{
    "lidar_model": "RPLIDAR S2",
    "section": "A20" ,
    "ranges": [1.1, "inf", 4.4]
}