@baseUrl = http://140.112.183.138:3000


###
# Demo specify image (use patrol type to continue upload same demo instence)
# for more than 1 picture:"demo_img_id=15433,15434...")
###
POST {{baseUrl}}/monitor/demo/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

demo_img_id=16412, 16675&straw=false&source=manual


###
# RPi upload with detection test (predict the picture immediately)
###


###
# [record view] toggle detection
###
POST {{baseUrl}}/record/toggleDetection HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

status=start


###
# record preview test, shows the latest three image info.
###
POST {{baseUrl}}/record/preview
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

section=C5
