@baseUrl = http://140.112.183.138:3000

###
# [Spray] update vehicle data
###
POST {{baseUrl}}/spray/vehicleData/ HTTP/1.1
content-type: application/json

{
    "uwb_coordinates": [100, 250],
    "battery_level": 80,
    "sprayed_pesticide": 30,
    "remaining_pesticide": 70
}

###
# [Spray] get vehicle data
###
GET {{baseUrl}}/spray/vehicleData/ HTTP/1.1


###
# [Spray] Updata spray experiment START
POST {{baseUrl}}/spray/expData/ HTTP/1.1
content-type: application/json

{
    "status": "start",
    "content": {
        "location": "Yizhu",
        "greenhouse": "B6",
        "fertilizers": [
            {"fertilizer_id": "3", "amount": 20.5},
            {"fertilizer_id": "1", "amount": 50.0}
        ],
        "note": "以200L的水、0.2L的柑桔精油、少量的活麗送稀釋而成。"
    }
}


###
# [Spray] Updata spray experiment STOP
POST {{baseUrl}}/spray/expData/ HTTP/1.1
content-type: application/json

{
    "status": "end",
    "content": {
        "total_water_used": 1000.5,
        "spray_target": [
            "yang-middle3",
            "yang-right1"
        ]
    }
}



###
# [Spray] query fertilizer list
###
GET {{baseUrl}}/spray/fertilizers/ HTTP/1.1


###
# [Spray] query fertilizer list
###
POST {{baseUrl}}/spray/fertilizers/ HTTP/1.1
content-type: application/json

{
    "name": "佈飛松"
}
